import type { EmmaCommand, AvatarExpression, CitationBlock, GeneratedFile } from "@/types/emma";

export interface StreamEnforcement {
  status: string;
  message: string | null;
  warningWindow: string | null;
  upgradeUrl: string | null;
}

export interface StreamDoneEvent {
  text: string;
  raw: string;
  commands: EmmaCommand[];
  routineId: string | null;
  expression: AvatarExpression | null;
  enforcement: StreamEnforcement | null;
  /** Citation blocks collected from citations_delta stream events. */
  citations?: CitationBlock[];
  /** Files generated by code_execution (skills). Download via /api/emma/files/download/[file_id]. */
  generatedFiles?: GeneratedFile[];
  /** Non-text content blocks (e.g. compaction blocks) to preserve in history. */
  compactionBlocks?: Record<string, unknown>[];
  /** Message ID — pass back as lastResponseId for diagnostics. */
  messageId?: string;
  /**
   * True when Claude refused the request (stop_reason === "refusal").
   * The client must NOT add this exchange to API history — roll back apiMessages
   * so the refused turn is not replayed on the next request.
   */
  refused?: boolean;
  /**
   * True when the input exceeded the model's context window
   * (stop_reason === "model_context_window_exceeded").
   * The client should hard-truncate apiMessages so the next turn fits.
   */
  contextWindowExceeded?: boolean;
}

interface StreamCallbacks {
  onDelta: (text: string) => void;
  onDone: (event: StreamDoneEvent) => void;
  onError: (error: string) => void;
  /** Called when a server-side tool (web_search, web_fetch) starts executing. */
  onToolStart?: (tool: string) => void;
}

/**
 * Consume SSE stream from /api/emma.
 *
 * Events:
 *   {"type":"delta","text":"..."} — streamed text chunk
 *   {"type":"done","text":"...","commands":[...],...} — final parsed response
 *   {"type":"error","text":"..."} — error message
 */
export async function streamEmmaResponse(
  body: Record<string, unknown>,
  callbacks: StreamCallbacks
): Promise<void> {
  const res = await fetch("/api/emma", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  // Non-streaming error response (JSON)
  if (!res.ok || !res.headers.get("content-type")?.includes("text/event-stream")) {
    try {
      const data = await res.json();
      callbacks.onError(data.error || "Something went wrong");
    } catch {
      callbacks.onError("Connection failed");
    }
    return;
  }

  const reader = res.body?.getReader();
  if (!reader) {
    callbacks.onError("No response body");
    return;
  }

  const decoder = new TextDecoder();
  let buffer = "";

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";

      for (const line of lines) {
        if (!line.startsWith("data: ")) continue;
        const data = line.slice(6).trim();
        if (!data) continue;

        try {
          const event = JSON.parse(data);

          switch (event.type) {
            case "delta":
              callbacks.onDelta(event.text);
              break;

            case "done":
              callbacks.onDone({
                text: event.text,
                raw: event.raw,
                commands: event.commands || [],
                routineId: event.routineId || null,
                expression: event.expression || null,
                enforcement: event.enforcement || null,
                citations: event.citations || undefined,
                generatedFiles: event.generatedFiles || undefined,
                compactionBlocks: event.compactionBlocks || undefined,
                messageId: event.messageId || undefined,
                refused: event.refused || undefined,
                contextWindowExceeded: event.contextWindowExceeded || undefined,
              });
              break;

            case "tool_start":
              callbacks.onToolStart?.(event.tool);
              break;

            case "error":
              callbacks.onError(event.text || "Unknown error");
              break;
          }
        } catch {
          // Skip malformed events
        }
      }
    }
  } catch {
    callbacks.onError("Stream interrupted");
  } finally {
    reader.releaseLock();
  }
}
