import { NextRequest, NextResponse } from "next/server";
import { getUser } from "@/lib/supabase/server";

const ANTHROPIC_FILES_URL = "https://api.anthropic.com/v1/files";

// GET /api/emma/files/download/[file_id]
// Proxies file content from the Anthropic Files API to the client.
// Used for files generated by code_execution (Agent Skills).
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ file_id: string }> }
) {
  const user = await getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return NextResponse.json({ error: "ANTHROPIC_API_KEY not set" }, { status: 500 });

  const { file_id } = await params;

  // Fetch metadata first to get the filename and media_type
  const metaRes = await fetch(`${ANTHROPIC_FILES_URL}/${file_id}`, {
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "anthropic-beta": "files-api-2025-04-14",
    },
  });

  if (!metaRes.ok) {
    const status = metaRes.status === 404 ? 404 : 502;
    return NextResponse.json({ error: "File not found" }, { status });
  }

  const meta = await metaRes.json();
  const filename: string = meta.filename ?? file_id;
  const mediaType: string = meta.media_type ?? "application/octet-stream";

  // Fetch file content
  const contentRes = await fetch(`${ANTHROPIC_FILES_URL}/${file_id}/content`, {
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "anthropic-beta": "files-api-2025-04-14",
    },
  });

  if (!contentRes.ok) {
    return NextResponse.json({ error: "Failed to fetch file content" }, { status: 502 });
  }

  const buffer = await contentRes.arrayBuffer();

  return new Response(buffer, {
    headers: {
      "Content-Type": mediaType,
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(buffer.byteLength),
      "Cache-Control": "private, max-age=300",
    },
  });
}
