import type { Metadata } from "next";
import PublicInfoPage, { type PublicInfoSection } from "@/components/landing/PublicInfoPage";

export const metadata: Metadata = {
  title: "Terms of Service | Emma",
  description:
    "The terms that govern use of Emma during closed beta: AI output limits, autonomous actions, billing, acceptable use, and liability.",
};

const sections: PublicInfoSection[] = [
  {
    title: "Agreement",
    body: "By creating an account or using Emma you agree to these terms and to the Privacy Policy. If you do not agree, do not use the service. Emma is currently in closed beta; access is gated by a waitlist and may be changed or revoked while the beta runs. Last updated: July 3, 2026.",
  },
  {
    title: "What Emma is",
    body: "Emma is an AI companion and workspace assistant: a persistent persona with memory, optional voice and avatar, and the ability to take actions in services you connect (email, calendar, files, chat, notes, CRM). Emma is software, not a person, and not a substitute for professional advice of any kind — medical, legal, financial, or otherwise.",
  },
  {
    title: "AI output",
    body: "Emma's responses are generated by AI language models and may be incomplete, out of date, or simply wrong. Review outputs before relying on them for anything important. You are responsible for decisions you make and actions you approve based on Emma's output.",
  },
  {
    title: "Autonomous actions and integrations",
    body: "When you connect an integration, you authorize Emma to act on your data in that service when you request it or when an automation you configured runs. Higher-risk actions require your explicit approval before they execute. You remain responsible for the external effects of actions you approve, for the accounts you connect, and for complying with each connected service's own terms. Disconnect an integration at any time in Settings → Integrations.",
  },
  {
    title: "Your keys",
    body: "Some features use credentials you supply (for example an ElevenLabs API key for voice, or a custom MCP server). You are responsible for those credentials, for the costs they incur with the third-party provider, and for having the right to use them. Emma stores supplied keys encrypted and uses them only to provide the feature you connected them for.",
  },
  {
    title: "Acceptable use",
    body: "You agree not to:",
    items: [
      "Use Emma for unlawful activity or to harm others.",
      "Attempt to bypass usage limits, plan enforcement, security controls, or content protections (including prompt-injection attacks).",
      "Probe, disrupt, or overload the service or its providers.",
      "Use Emma to generate or distribute malware, spam, or deceptive content.",
      "Resell or provide access to the service to third parties without permission.",
    ],
  },
  {
    title: "Plans and billing",
    body: "Paid plans are billed through LemonSqueezy, our merchant of record. Usage is metered per 5-hour rolling window; when a window's budget is used up, responses pause until the window resets or you purchase an Extra Response Pack. Cancelling a subscription keeps paid access until the end of the current billing period, after which the account falls back to Free limits. If a payment fails, access may be reduced during the recovery period and ends if payment is not recovered. Prices and limits are shown at checkout and in Settings → Billing. During beta, refunds are handled manually — contact the team via the Support page.",
  },
  {
    title: "Your content",
    body: "You own the content you bring to Emma — messages, documents, and data in connected services. You grant us the limited rights needed to operate the service: storing, encrypting, and processing your content (including sending it to the AI providers listed in the Privacy Policy) solely to provide Emma's features. We do not use your conversations to train models.",
  },
  {
    title: "Availability and beta status",
    body: "Emma is provided as-is during closed beta. Features may change, break, or be removed; documented limitations are listed on the Known Limitations page. We do not promise any particular uptime, support response time, or feature availability during beta.",
  },
  {
    title: "Disclaimer and liability",
    body: "To the maximum extent permitted by law, Emma is provided without warranties of any kind, express or implied, and our total liability for any claim arising out of the service is limited to the amount you paid for the service in the twelve months before the claim. Nothing in these terms excludes liability that cannot be excluded by law.",
  },
  {
    title: "Termination",
    body: "You can stop using Emma and delete your data at any time (see the Privacy Policy for how deletion works). We may suspend or terminate accounts that violate these terms or abuse the service, and may discontinue the beta with reasonable notice.",
  },
  {
    title: "Changes",
    body: "We may update these terms as the product evolves and will revise the date at the top. Material changes will be communicated in the app or by email; continued use after a change means you accept the updated terms.",
  },
  {
    title: "Legal review status",
    body: "These terms are written and maintained by the Emma team to accurately describe how the service currently works. They have not yet been reviewed by qualified counsel; that review is planned before public launch, as also noted on the Known Limitations page.",
  },
];

export default function TermsPage() {
  return (
    <PublicInfoPage
      eyebrow="Terms"
      title="Terms of Service"
      intro="The rules that govern Emma during closed beta — written to match what the product actually does today, with the beta's limits stated plainly rather than papered over."
      sections={sections}
    />
  );
}
